apiVersion: v1
kind: Secret
metadata:
  name: frontend-env
  namespace: quickfood
type: Opaque
data:
  NODE_ENV: cHJvZHVjdGlvbg==
  VITE_IMAGE_HOSTING_KEY: MDFlNTU4NDg3NzIzYTk5OWViODljYTJlNmViNzVjYjI=
  VITE_APIKEY: QUl6YVN5QzJFUFk5VU9PZ3lwalZ4cXhLWVVKM2dZMUIxS2xuSVpj
  VITE_AUTHDOMAIN: cXVpY2tmb29kLWFwcC5maXJlYmFzZWFwcC5jb20=
  VITE_PROJECTID: cXVpY2tmb29kLWFwcA==
  VITE_STORAGEBUCKET: cXVpY2tmb29kLWFwcC5hcHBzcG90LmNvbQ==
  VITE_MESSAGINGSENDERID: MzI2MTkwNTc0MjE1
  VITE_APPID: MTozMjYxOTA1NzQyMTU6d2ViOjdlMGVkMjE0NTg2ZDM5NTJhY2U2MjI=
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: quickfood
type: Opaque
data:
  NODE_ENV: cHJvZHVjdGlvbg==
  MONGODB_URI: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvZGI6MjcwMTcvZGJuYW1lP2F1dGhTb3VyY2U9YWRtaW4=
  PORT: NjAwMQ==
  MONGO_URI: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvZGI6MjcwMTcvZGJuYW1lP2F1dGhTb3VyY2U9YWRtaW4=
  ACCESS_TOKEN_SECRET: ZmNiODEyNTFiMDE0YzYzMjE4MDViNTRjNzdiODFmZjAxYTFkOGJjYjg5YTAzM2E3MDY1OTdiNWFlYzY4OGMwMTUzZmM4ODM3M2Y4MTFkOWYwYTM3MzQ3ZjIxMDY1MTEzN2ZkN2Y1YzQyY2MwMjZhMjFmZjdjOWFhOTFlYTViYmQ=
  STRIPE_KEY: c2tfdGVzdF81MU90ckxrU0dKeVUxU1NUc1NnN2VIQTZzQ2hqUVZBcmF2SkN1V2hPRzdVOFlSQk40UkpUb1JYS2VNWmdWWWJYNk1HRkdLWTl2NlhCdmFVOXJuN09zc0ZVdTAwN3d1Z3pMdFo=
